// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": process.env.NEXT_PUBLIC_USER_POOL_ID || "us-east-1_ZNwA1XBAt",
    "aws_user_pools_web_client_id": process.env.NEXT_PUBLIC_USER_POOL_CLIENT_ID || "1mlmpcdgqovg1i55vvfki35b1v",
    "oauth": {},
    "aws_cognito_username_attributes": ["EMAIL"],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": ["EMAIL", "GIVEN_NAME", "ADDRESS"],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": ["EMAIL"],
    "aws_appsync_graphqlEndpoint": process.env.NEXT_PUBLIC_GRAPHQL_ENDPOINT || "https://fqhs2y3vlvfndk46swuyvklnrm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};

export default awsmobile; 